### ISSUE TITLE
超过2G的apk无法签名

### ISSUE THREAD

**Issue by yw-forGit** [jixiaoyong/ApkSigner#22]
### 系统类型

Windows

### 系统版本

win10

### 软件版本

最新

## 想要实现的功能
已经试过小于2G的apk是可以签名的，超过2G就报错了

## 遇到的问题
报错日志：
apk signer command: C:\Software\Android\sdk\build-tools\31.0.0\aapt.exe dump badging D:\SoftwareData\GData\apk\xxx.apk | grep 'package: name'
Unable to open 'D:\SoftwareData\GData\apk\xxx.apk' as zip archive
Exited with code: 1
apksigner.bat命令省略。。。
Exception in thread "main" java.io.FileNotFoundException: D:\SoftwareData\GData\apk\xxx_aligned.apk (系统找不到指定的文件。)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:381)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:88)
	at com.android.apksig.ApkSigner.sign(ApkSigner.java:190)
Exited with code: 1

## 尝试了如下方案，并未解决
网络搜索到，通常是路径问题和zipalign限制2G的问题，小2G没问题排除路径问题，推测为超过2G引发的。

### 功能/优化对应的步骤

是否可以优化？

感谢您的软件。

**Comment by yw-forGit** [comment]
已解决。
解决方法：
1、在Linux或mac执行zipalign
2、Windows上需要替换一下zipalign.exe
具体参考：https://blog.csdn.net/liuyanggofurther/article/details/128902682
